name: Feature Request
description: Suggest an idea for this project
title: '[Feature]: '
labels: ['enhancement', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand and evaluate your request.

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe
      placeholder: |
        I'm trying to [achieve goal] but I can't because [limitation]. 
        This makes it difficult to [use case] and results in [negative impact].
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: |
        I would like to see [feature] implemented with [specific details]. 
        This should work by [mechanism] and integrate with [existing features].
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        I've tried [alternative 1] but it didn't work because [reason]. 
        I also considered [alternative 2] but it has [drawbacks].

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Tool/Plugin
        - Transport Protocol
        - Security Enhancement
        - Performance Improvement
        - API Enhancement
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocker for my use case
        - High - Significant improvement needed
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What use case would this feature enable?
      placeholder: |
        This feature would enable me to [specific task] which is important because [reason].
        It would benefit [target users] by [specific benefit].

  - type: textarea
    id: implementation-details
    attributes:
      label: Implementation Details
      description: Any ideas on how this could be implemented?
      placeholder: |
        I think this could be implemented by [technical approach].
        It might require [dependencies] or changes to [existing code].

  - type: textarea
    id: mockups-examples
    attributes:
      label: Mockups / Examples
      description: Add any mockups, screenshots, or code examples
      render: typescript

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, links to references, or related issues

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmations
      description: Please confirm the following
      options:
        - label: I have searched existing issues for similar requests
          required: true
        - label: I have read the documentation
          required: true
        - label: This feature aligns with the project's goals
          required: true
